import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import NavBar from "./_sections/Navbar";
import Footer from "./_sections/Footer";
import "@/app/global.css";

export const metadata: Metadata = {
  title: "Moises",
  description: "Generated by create next app"
};

type Params = Promise<{ locale: "en" | "pt" }>;

export default async function LocaleLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: Params;
}) {
  const { locale } = await params;
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  const globalConfig = await getMessages();

  const { menu, footerMenu, social, helpText, copyright }: any =
    globalConfig.global;
  return (
    <html lang={locale}>
      <body className="bg-black">
        <NextIntlClientProvider messages={globalConfig}>
          <NavBar data={menu} />
          {children}
          <Footer data={{ footerMenu, social, helpText, copyright }} />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
