/* eslint-disable @typescript-eslint/no-explicit-any */
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";

import "@/app/global.css";
import NavBar from "./_sections/Navbar";

export const metadata: Metadata = {
  title: "Moises",
  description: "Generated by create next app"
};

export default async function LocaleLayout({
  children,
  params: { locale }
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  const data = await getMessages();

  const { menu } = data.global;

  return (
    <html lang={locale}>
      <body className="bg-black bg-hero-section bg-contain bg-right-top bg-no-repeat">
        <NextIntlClientProvider messages={data}>
          <NavBar data={menu} />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
